# Generated by Django 4.2.30 on 2026-04-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('DESPACHADA', 'Despachada'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=15)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'db_table': 'solicitudes',
                'ordering': ['-created_at'],
            },
        ),
    ]
