# Generated by Django 4.2.30 on 2026-04-28 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        ('inventario', '0002_initial'),
        ('solicitudes', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.PositiveIntegerField()),
                ('cantidad_aprobada', models.PositiveIntegerField(blank=True, null=True)),
                ('lote', models.ForeignKey(blank=True, help_text='Asignado por el gestor al aprobar', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalle_solicitudes', to='inventario.lote')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalle_solicitudes', to='catalogo.producto')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='solicitudes.solicitud')),
            ],
            options={
                'verbose_name': 'Detalle de Solicitud',
                'verbose_name_plural': 'Detalles de Solicitud',
                'db_table': 'detalle_solicitudes',
            },
        ),
    ]
