# Generated by Django 4.2.30 on 2026-04-28 19:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_compra', models.CharField(help_text='Número de orden de compra', max_length=100)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('cantidad_inicial', models.PositiveIntegerField()),
                ('cantidad_disponible', models.PositiveIntegerField()),
                ('cantidad_reservada', models.PositiveIntegerField(default=0)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_caducidad', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('AGOTADO', 'Agotado'), ('VENCIDO', 'Vencido'), ('BAJA', 'Dado de baja')], default='ACTIVO', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'db_table': 'lotes',
                'ordering': ['fecha_caducidad', 'fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('DESPACHO', 'Despacho'), ('BAJA', 'Baja'), ('RESERVA', 'Reserva'), ('LIBERACION', 'Liberación')], max_length=15)),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('stock_anterior', models.PositiveIntegerField(help_text='Stock disponible antes del movimiento')),
                ('stock_posterior', models.PositiveIntegerField(help_text='Stock disponible después del movimiento')),
                ('motivo', models.TextField(blank=True, help_text='Obligatorio para bajas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'db_table': 'movimientos',
                'ordering': ['-created_at'],
            },
        ),
    ]
